# Generated by Django 4.2.2 on 2023-06-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
