# Generated by Django 4.2.2 on 2023-06-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
