# Generated by Django 4.2.2 on 2023-06-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
