# Generated by Django 4.2.2 on 2023-07-03 00:28

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_address_patient_city_patient_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(upload_to=patients.models.patient_image_path),
        ),
    ]
