# Generated by Django 4.2.2 on 2023-07-03 20:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
