# Generated by Django 4.2.2 on 2023-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_birth_date_alter_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
