# Generated by Django 4.2.2 on 2023-07-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
